import { defineVisualIdentity, type VisualIdentity } from "./visual-identity"

/**
 * Palette registry — the single source of truth for hot-swappable color
 * themes. Each entry is a `VisualIdentity` whose `light` / `dark` token
 * overrides are applied as inline custom properties on `<html>` by
 * ThemeProvider at runtime.
 *
 * The "onerep" entry has no overrides: it inherits the CSS defaults from
 * `styles/palette.css`. Any other entry swaps the product accent and
 * status hues while keeping surfaces, typography, and spacing untouched.
 *
 * To add a new palette:
 *   1. Duplicate one of the entries below.
 *   2. Override the token values you want to change.
 *   3. Register it in `PALETTES`.
 *
 * Hot-swap at runtime via `setIdentity("palette-id")` from the ThemeProvider
 * context, or from the settings UI.
 */
export const ONEREPALETTE: VisualIdentity = defineVisualIdentity({
  id: "onerep",
  label: "OneRep",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
})

export const DUSK_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "dusk",
  label: "Dusk",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  light: {
    "--accent-food": "#a0522d",
    "--accent-food-bg": "color-mix(in srgb, #a0522d 8%, transparent)",
    "--accent-water": "#2e6b8a",
    "--accent-water-bg": "color-mix(in srgb, #2e6b8a 8%, transparent)",
    "--accent-supplement": "#4a7c50",
    "--accent-supplement-bg": "color-mix(in srgb, #4a7c50 8%, transparent)",
    "--accent-workout": "#6b5b95",
    "--accent-workout-bg": "color-mix(in srgb, #6b5b95 8%, transparent)",
    "--accent-training-hero": "#2a7d6e",
    "--accent-progress": "#8b5e8b",
    "--accent-health": "#2a7a8a",
    "--accent-retro": "#b8860b",
    "--accent-retro-bg": "color-mix(in srgb, #b8860b 14%, transparent)",
    "--accent-schedule": "#4a7aa0",
    "--accent-schedule-bg": "color-mix(in srgb, #4a7aa0 15%, transparent)",
    "--accent-progress-bg": "color-mix(in srgb, #8b5e8b 8%, transparent)",
    "--status-success": "#3a8a5a",
    "--status-warning": "#b8860b",
    "--status-error": "#a03040",
    "--macro-protein": "#a0522d",
    "--macro-carbs": "#2e6b8a",
    "--macro-fat": "#8b5e8b",
    "--surface-app": "#f5efe4",
    "--surface-panel": "#fdf9f0",
    "--surface-raised": "#fffdf8",
    "--surface-elevated": "#fffdf8",
    "--surface-canvas": "#ece5d3",
    "--secondary": "#eae2d2",
    "--muted": "#eae2d2",
    "--accent": "#eae2d2",
    "--hero-wash-tint": "38%",
    "--hero-wash-crown": "16%",
    "--hero-mesh-tint": "34%",
    "--radius": "0.625rem",
    "--radius-row": "0.75rem",
    "--radius-control": "1rem",
    "--radius-panel": "1.25rem",
    "--radius-sheet": "1.5rem",
    "--font-heading":
      'Georgia, "Iowan Old Style", "Palatino Linotype", Palatino, "Times New Roman", serif',
  },
  dark: {
    "--accent-food": "#e8925a",
    "--accent-water": "#5ab0e0",
    "--accent-supplement": "#70c078",
    "--accent-workout": "#9a8aff",
    "--accent-training-hero": "#4ac0a8",
    "--accent-progress": "#d090d0",
    "--accent-health": "#5ac0d0",
    "--status-success": "#60c080",
    "--status-warning": "#e8b850",
    "--status-error": "#e87088",
    "--macro-protein": "#e8925a",
    "--macro-carbs": "#5ab0e0",
    "--macro-fat": "#d090d0",
    "--surface-app": "#100d0a",
    "--surface-panel": "#1a1512",
    "--surface-raised": "#221b15",
    "--surface-elevated": "#292019",
    "--surface-canvas": "#0c0a08",
    "--secondary": "#26211b",
    "--muted": "#26211b",
    "--accent": "#26211b",
    "--hero-wash-tint": "20%",
    "--hero-mesh-tint": "30%",
    "--radius": "0.625rem",
    "--radius-row": "0.75rem",
    "--radius-control": "1rem",
    "--radius-panel": "1.25rem",
    "--radius-sheet": "1.5rem",
    "--font-heading":
      'Georgia, "Iowan Old Style", "Palatino Linotype", Palatino, "Times New Roman", serif',
  },
})

export const SLATE_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "slate",
  label: "Slate",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  light: {
    "--accent-food": "#6b5344",
    "--accent-water": "#3a6888",
    "--accent-supplement": "#4a7a4e",
    "--accent-workout": "#5a5a8a",
    "--accent-training-hero": "#2a7a70",
    "--accent-progress": "#7a5a78",
    "--accent-health": "#2a7080",
    "--accent-retro": "#8a7040",
    "--accent-schedule": "#4a70a0",
    "--status-success": "#3a7a4a",
    "--status-warning": "#8a7040",
    "--status-error": "#8a3040",
    "--macro-protein": "#6b5344",
    "--macro-carbs": "#3a6888",
    "--macro-fat": "#7a5a78",
    "--surface-app": "#eef0f2",
    "--surface-panel": "#f8f9fa",
    "--surface-raised": "#ffffff",
    "--surface-elevated": "#ffffff",
    "--surface-canvas": "#e4e7ea",
    "--secondary": "#e4e7ea",
    "--muted": "#e4e7ea",
    "--accent": "#e4e7ea",
    "--hero-wash-tint": "16%",
    "--hero-mesh-tint": "16%",
    "--radius": "0.25rem",
    "--radius-row": "0.375rem",
    "--radius-control": "0.5rem",
    "--radius-panel": "0.625rem",
    "--radius-sheet": "0.75rem",
    "--font-sans":
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", Inter, "Segoe UI", sans-serif',
  },
  dark: {
    "--accent-food": "#d89060",
    "--accent-water": "#60b0e0",
    "--accent-supplement": "#70c880",
    "--accent-workout": "#8888e0",
    "--accent-training-hero": "#50c8b0",
    "--accent-progress": "#c888c8",
    "--accent-health": "#50b8d0",
    "--status-success": "#58c078",
    "--status-warning": "#e0b850",
    "--status-error": "#e07890",
    "--macro-protein": "#d89060",
    "--macro-carbs": "#60b0e0",
    "--macro-fat": "#c888c8",
    "--surface-app": "#0b0d0f",
    "--surface-panel": "#14171a",
    "--surface-raised": "#1b1f24",
    "--surface-elevated": "#21262c",
    "--surface-canvas": "#090b0d",
    "--secondary": "#1e2329",
    "--muted": "#1e2329",
    "--accent": "#1e2329",
    "--hero-wash-tint": "10%",
    "--hero-mesh-tint": "18%",
    "--radius": "0.25rem",
    "--radius-row": "0.375rem",
    "--radius-control": "0.5rem",
    "--radius-panel": "0.625rem",
    "--radius-sheet": "0.75rem",
    "--font-sans":
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", Inter, "Segoe UI", sans-serif',
  },
})

export const FOREST_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "forest",
  label: "Forest",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  light: {
    "--accent-food": "#8a6d1a",
    "--accent-food-bg": "color-mix(in srgb, #8a6d1a 8%, transparent)",
    "--accent-water": "#1e7a6e",
    "--accent-water-bg": "color-mix(in srgb, #1e7a6e 8%, transparent)",
    "--accent-supplement": "#3d8b37",
    "--accent-supplement-bg": "color-mix(in srgb, #3d8b37 8%, transparent)",
    "--accent-workout": "#2f6b4f",
    "--accent-workout-bg": "color-mix(in srgb, #2f6b4f 8%, transparent)",
    "--accent-training-hero": "#2e7d4f",
    "--accent-progress": "#6b8e4e",
    "--accent-health": "#2e8b57",
    "--accent-retro": "#96700a",
    "--accent-retro-bg": "color-mix(in srgb, #96700a 14%, transparent)",
    "--accent-schedule": "#3f7d5d",
    "--accent-schedule-bg": "color-mix(in srgb, #3f7d5d 15%, transparent)",
    "--accent-progress-bg": "color-mix(in srgb, #6b8e4e 8%, transparent)",
    "--status-success": "#2f7d3a",
    "--status-warning": "#96700a",
    "--status-error": "#9e3a32",
    "--macro-protein": "#8a6d1a",
    "--macro-carbs": "#1e7a6e",
    "--macro-fat": "#6b8e4e",
    "--surface-app": "#edf0e4",
    "--surface-panel": "#f7f9ef",
    "--surface-raised": "#fdfff7",
    "--surface-elevated": "#fdfff7",
    "--surface-canvas": "#e0e5d2",
    "--secondary": "#e3e7d6",
    "--muted": "#e3e7d6",
    "--accent": "#e3e7d6",
    "--hero-wash-tint": "34%",
    "--hero-mesh-tint": "32%",
    "--radius": "0.75rem",
    "--radius-row": "0.875rem",
    "--radius-control": "1.125rem",
    "--radius-panel": "1.375rem",
    "--radius-sheet": "1.75rem",
    "--font-sans":
      'ui-rounded, "SF Pro Rounded", "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
  },
  dark: {
    "--accent-food": "#e0b34e",
    "--accent-water": "#4ec9b0",
    "--accent-supplement": "#7dd87d",
    "--accent-workout": "#9ccc65",
    "--accent-training-hero": "#64d8b8",
    "--accent-progress": "#b8d87d",
    "--accent-health": "#5fd0c0",
    "--status-success": "#5fce7a",
    "--status-warning": "#e3b341",
    "--status-error": "#e08080",
    "--macro-protein": "#e0b34e",
    "--macro-carbs": "#4ec9b0",
    "--macro-fat": "#b8d87d",
    "--surface-app": "#0b0e09",
    "--surface-panel": "#141812",
    "--surface-raised": "#1a2015",
    "--surface-elevated": "#202719",
    "--surface-canvas": "#090c07",
    "--secondary": "#1c2218",
    "--muted": "#1c2218",
    "--accent": "#1c2218",
    "--hero-wash-tint": "18%",
    "--hero-mesh-tint": "28%",
    "--radius": "0.75rem",
    "--radius-row": "0.875rem",
    "--radius-control": "1.125rem",
    "--radius-panel": "1.375rem",
    "--radius-sheet": "1.75rem",
    "--font-sans":
      'ui-rounded, "SF Pro Rounded", "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
  },
})

export const OCEAN_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "ocean",
  label: "Ocean",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  light: {
    "--accent-food": "#c05a2e",
    "--accent-food-bg": "color-mix(in srgb, #c05a2e 8%, transparent)",
    "--accent-water": "#1668a8",
    "--accent-water-bg": "color-mix(in srgb, #1668a8 8%, transparent)",
    "--accent-supplement": "#1a8a8a",
    "--accent-supplement-bg": "color-mix(in srgb, #1a8a8a 8%, transparent)",
    "--accent-workout": "#3f5fa8",
    "--accent-workout-bg": "color-mix(in srgb, #3f5fa8 8%, transparent)",
    "--accent-training-hero": "#0f7d8a",
    "--accent-progress": "#4f7fb8",
    "--accent-health": "#166e9e",
    "--accent-retro": "#8a6d1a",
    "--accent-retro-bg": "color-mix(in srgb, #8a6d1a 14%, transparent)",
    "--accent-schedule": "#2f6fa8",
    "--accent-schedule-bg": "color-mix(in srgb, #2f6fa8 15%, transparent)",
    "--accent-progress-bg": "color-mix(in srgb, #4f7fb8 8%, transparent)",
    "--status-success": "#1f7d5c",
    "--status-warning": "#96700a",
    "--status-error": "#a8324a",
    "--macro-protein": "#c05a2e",
    "--macro-carbs": "#1668a8",
    "--macro-fat": "#4f7fb8",
    "--surface-app": "#e9eff4",
    "--surface-panel": "#f4f8fb",
    "--surface-raised": "#fdfeff",
    "--surface-elevated": "#fdfeff",
    "--surface-canvas": "#dbe4ec",
    "--secondary": "#dde6ee",
    "--muted": "#dde6ee",
    "--accent": "#dde6ee",
    "--hero-wash-tint": "36%",
    "--hero-mesh-tint": "32%",
    "--radius": "0.5rem",
    "--radius-row": "0.5rem",
    "--radius-control": "0.75rem",
    "--radius-panel": "1rem",
    "--radius-sheet": "1.5rem",
    "--font-sans":
      '"Avenir Next", Avenir, "SF Pro Text", "Segoe UI", sans-serif',
  },
  dark: {
    "--accent-food": "#f0905a",
    "--accent-water": "#4ea8e8",
    "--accent-supplement": "#4ed0c0",
    "--accent-workout": "#7a90f0",
    "--accent-training-hero": "#3fc0d0",
    "--accent-progress": "#7ab8e8",
    "--accent-health": "#4ab8e0",
    "--status-success": "#4ecf8a",
    "--status-warning": "#e8b850",
    "--status-error": "#f07890",
    "--macro-protein": "#f0905a",
    "--macro-carbs": "#4ea8e8",
    "--macro-fat": "#7ab8e8",
    "--surface-app": "#090d11",
    "--surface-panel": "#12181e",
    "--surface-raised": "#172027",
    "--surface-elevated": "#1d2731",
    "--surface-canvas": "#070a0d",
    "--secondary": "#1a222b",
    "--muted": "#1a222b",
    "--accent": "#1a222b",
    "--hero-wash-tint": "20%",
    "--hero-mesh-tint": "30%",
    "--radius": "0.5rem",
    "--radius-row": "0.5rem",
    "--radius-control": "0.75rem",
    "--radius-panel": "1rem",
    "--radius-sheet": "1.5rem",
    "--font-sans":
      '"Avenir Next", Avenir, "SF Pro Text", "Segoe UI", sans-serif',
  },
})

export const BLOSSOM_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "blossom",
  label: "Blossom",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  light: {
    "--accent-food": "#b23a5b",
    "--accent-food-bg": "color-mix(in srgb, #b23a5b 8%, transparent)",
    "--accent-water": "#5b6fb0",
    "--accent-water-bg": "color-mix(in srgb, #5b6fb0 8%, transparent)",
    "--accent-supplement": "#3f8b66",
    "--accent-supplement-bg": "color-mix(in srgb, #3f8b66 8%, transparent)",
    "--accent-workout": "#8b4a8b",
    "--accent-workout-bg": "color-mix(in srgb, #8b4a8b 8%, transparent)",
    "--accent-training-hero": "#a83a6b",
    "--accent-progress": "#c06a9e",
    "--accent-health": "#93386b",
    "--accent-retro": "#a8760a",
    "--accent-retro-bg": "color-mix(in srgb, #a8760a 14%, transparent)",
    "--accent-schedule": "#7a5f9e",
    "--accent-schedule-bg": "color-mix(in srgb, #7a5f9e 15%, transparent)",
    "--accent-progress-bg": "color-mix(in srgb, #c06a9e 8%, transparent)",
    "--status-success": "#3f8b5c",
    "--status-warning": "#a8760a",
    "--status-error": "#a82e4a",
    "--macro-protein": "#b23a5b",
    "--macro-carbs": "#5b6fb0",
    "--macro-fat": "#c06a9e",
    "--surface-app": "#f5ecef",
    "--surface-panel": "#fdf5f7",
    "--surface-raised": "#fffdfd",
    "--surface-elevated": "#fffdfd",
    "--surface-canvas": "#eadde2",
    "--secondary": "#eadfe3",
    "--muted": "#eadfe3",
    "--accent": "#eadfe3",
    "--hero-wash-tint": "40%",
    "--hero-wash-crown": "18%",
    "--hero-mesh-tint": "36%",
    "--radius": "1rem",
    "--radius-row": "1rem",
    "--radius-control": "1.25rem",
    "--radius-panel": "1.5rem",
    "--radius-sheet": "2rem",
    "--font-sans":
      'ui-rounded, "SF Pro Rounded", "Hiragino Maru Gothic ProN", "Segoe UI", Roboto, sans-serif',
  },
  dark: {
    "--accent-food": "#f07890",
    "--accent-water": "#8a90e8",
    "--accent-supplement": "#5fd09a",
    "--accent-workout": "#c080d8",
    "--accent-training-hero": "#f06090",
    "--accent-progress": "#e8a0c8",
    "--accent-health": "#b080e8",
    "--status-success": "#5fd89a",
    "--status-warning": "#e8b850",
    "--status-error": "#f07888",
    "--macro-protein": "#f07890",
    "--macro-carbs": "#8a90e8",
    "--macro-fat": "#e8a0c8",
    "--surface-app": "#100a0d",
    "--surface-panel": "#1a1216",
    "--surface-raised": "#22161c",
    "--surface-elevated": "#2a1b22",
    "--surface-canvas": "#0d080a",
    "--secondary": "#241a1f",
    "--muted": "#241a1f",
    "--accent": "#241a1f",
    "--hero-wash-tint": "22%",
    "--hero-mesh-tint": "32%",
    "--radius": "1rem",
    "--radius-row": "1rem",
    "--radius-control": "1.25rem",
    "--radius-panel": "1.5rem",
    "--radius-sheet": "2rem",
    "--font-sans":
      'ui-rounded, "SF Pro Rounded", "Hiragino Maru Gothic ProN", "Segoe UI", Roboto, sans-serif',
  },
})

/** All registered palettes. The first entry is the default. */
export const PALETTES: readonly VisualIdentity[] = [
  ONEREPALETTE,
  DUSK_PALETTE,
  SLATE_PALETTE,
  FOREST_PALETTE,
  OCEAN_PALETTE,
  BLOSSOM_PALETTE,
] as const
