import { defineVisualIdentity, type VisualIdentity } from "./visual-identity"

/**
 * Palette registry — the single source of truth for hot-swappable color
 * themes. Each entry is a `VisualIdentity` whose `light` / `dark` token
 * overrides are applied as inline custom properties on `<html>` by
 * ThemeProvider at runtime.
 *
 * The "onerep" entry has no overrides: it inherits the CSS defaults from
 * `styles/palette.css`. Any other entry swaps the product accent and
 * status hues while keeping surfaces, typography, and spacing untouched.
 *
 * To add a new palette:
 *   1. Duplicate one of the entries below.
 *   2. Override the token values you want to change.
 *   3. Register it in `PALETTES`.
 *
 * Hot-swap at runtime via `setIdentity("palette-id")` from the ThemeProvider
 * context, or from the settings UI.
 */
export const ONEREPALETTE: VisualIdentity = defineVisualIdentity({
  id: "onerep",
  label: "OneRep",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
})

export const DUSK_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "dusk",
  label: "Dusk",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  tokens: {
    "--identity-home-gradient":
      "radial-gradient(105% 72% at 94% -12%, color-mix(in oklab, var(--accent-food) 38%, transparent) 0%, transparent 68%), radial-gradient(82% 76% at -8% 34%, color-mix(in oklab, var(--accent-progress) 30%, transparent) 0%, transparent 72%), linear-gradient(145deg, color-mix(in oklab, var(--accent-training-hero) 16%, transparent) 0%, transparent 58%)",
    "--identity-page-gradient":
      "radial-gradient(116% 74% at 88% -8%, color-mix(in oklab, var(--hero-accent, var(--accent-food)) 38%, transparent) 0%, transparent 69%), radial-gradient(82% 68% at -8% 46%, color-mix(in oklab, var(--accent-food) 22%, transparent) 0%, transparent 72%), linear-gradient(160deg, color-mix(in oklab, var(--accent-progress) 15%, transparent) 0%, transparent 60%)",
    "--identity-hero-mask":
      "linear-gradient(168deg, #000 0%, #000 45%, transparent 92%)",
    "--identity-hero-height": "min(48rem, 84svh)",
  },
  light: {
    "--accent-food": "#a0522d",
    "--accent-food-bg": "color-mix(in srgb, #a0522d 8%, transparent)",
    "--accent-water": "#2e6b8a",
    "--accent-water-bg": "color-mix(in srgb, #2e6b8a 8%, transparent)",
    "--accent-supplement": "#4a7c50",
    "--accent-supplement-bg": "color-mix(in srgb, #4a7c50 8%, transparent)",
    "--accent-workout": "#6b5b95",
    "--accent-workout-bg": "color-mix(in srgb, #6b5b95 8%, transparent)",
    "--accent-training-hero": "#2a7d6e",
    "--accent-progress": "#8b5e8b",
    "--accent-health": "#2a7a8a",
    "--accent-retro": "#b8860b",
    "--accent-retro-bg": "color-mix(in srgb, #b8860b 14%, transparent)",
    "--accent-schedule": "#4a7aa0",
    "--accent-schedule-bg": "color-mix(in srgb, #4a7aa0 15%, transparent)",
    "--accent-progress-bg": "color-mix(in srgb, #8b5e8b 8%, transparent)",
    "--status-success": "#3a8a5a",
    "--status-warning": "#b8860b",
    "--status-error": "#a03040",
    "--macro-protein": "#a0522d",
    "--macro-carbs": "#2e6b8a",
    "--macro-fat": "#8b5e8b",
    "--surface-app": "#f5efe4",
    "--surface-panel": "#fdf9f0",
    "--surface-raised": "#fffdf8",
    "--surface-elevated": "#fffdf8",
    "--surface-canvas": "#ece5d3",
    "--secondary": "#eae2d2",
    "--muted": "#eae2d2",
    "--accent": "#eae2d2",
    "--hero-wash-tint": "38%",
    "--hero-wash-crown": "16%",
    "--hero-mesh-tint": "34%",
    "--radius": "0.625rem",
    "--radius-row": "0.75rem",
    "--radius-control": "1rem",
    "--radius-panel": "1.25rem",
    "--radius-sheet": "1.5rem",
    "--font-heading":
      'Georgia, "Iowan Old Style", "Palatino Linotype", Palatino, "Times New Roman", serif',
  },
  dark: {
    "--accent-food": "#efab82",
    "--accent-water": "#83c2e9",
    "--accent-supplement": "#97cf9c",
    "--accent-workout": "#b5a8ff",
    "--accent-training-hero": "#7bd0ba",
    "--accent-progress": "#dbaedb",
    "--accent-health": "#88d0db",
    "--status-success": "#8bd1a1",
    "--status-warning": "#efca83",
    "--status-error": "#efa0b0",
    "--macro-protein": "#efab82",
    "--macro-carbs": "#83c2e9",
    "--macro-fat": "#dbaedb",
    "--surface-app": "#141211",
    "--surface-panel": "#1d1a18",
    "--surface-raised": "#25211e",
    "--surface-elevated": "#2c2723",
    "--surface-canvas": "#100e0d",
    "--secondary": "#292521",
    "--muted": "#292521",
    "--accent": "#292521",
    "--hero-wash-tint": "20%",
    "--hero-mesh-tint": "30%",
    "--radius": "0.625rem",
    "--radius-row": "0.75rem",
    "--radius-control": "1rem",
    "--radius-panel": "1.25rem",
    "--radius-sheet": "1.5rem",
    "--font-heading":
      'Georgia, "Iowan Old Style", "Palatino Linotype", Palatino, "Times New Roman", serif',
  },
})

export const SLATE_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "slate",
  label: "Slate",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  tokens: {
    "--identity-home-gradient":
      "linear-gradient(128deg, color-mix(in oklab, var(--accent-water) 24%, transparent) 0%, transparent 43%), linear-gradient(308deg, color-mix(in oklab, var(--accent-progress) 17%, transparent) 0%, transparent 56%), radial-gradient(90% 42% at 50% -8%, color-mix(in oklab, var(--foreground) 9%, transparent) 0%, transparent 76%)",
    "--identity-page-gradient":
      "linear-gradient(132deg, color-mix(in oklab, var(--hero-accent, var(--accent-food)) 28%, transparent) 0%, transparent 46%), linear-gradient(312deg, color-mix(in oklab, var(--accent-water) 14%, transparent) 0%, transparent 58%), radial-gradient(86% 36% at 54% 0%, color-mix(in oklab, var(--foreground) 8%, transparent) 0%, transparent 78%)",
    "--identity-hero-mask":
      "linear-gradient(156deg, #000 0%, #000 38%, transparent 88%)",
    "--identity-hero-height": "min(42rem, 74svh)",
  },
  light: {
    "--accent-food": "#6b5344",
    "--accent-water": "#3a6888",
    "--accent-supplement": "#4a7a4e",
    "--accent-workout": "#5a5a8a",
    "--accent-training-hero": "#2a7a70",
    "--accent-progress": "#7a5a78",
    "--accent-health": "#2a7080",
    "--accent-retro": "#8a7040",
    "--accent-schedule": "#4a70a0",
    "--status-success": "#3a7a4a",
    "--status-warning": "#8a7040",
    "--status-error": "#8a3040",
    "--macro-protein": "#6b5344",
    "--macro-carbs": "#3a6888",
    "--macro-fat": "#7a5a78",
    "--surface-app": "#eef0f2",
    "--surface-panel": "#f8f9fa",
    "--surface-raised": "#ffffff",
    "--surface-elevated": "#ffffff",
    "--surface-canvas": "#e4e7ea",
    "--secondary": "#e4e7ea",
    "--muted": "#e4e7ea",
    "--accent": "#e4e7ea",
    "--hero-wash-tint": "16%",
    "--hero-mesh-tint": "16%",
    "--radius": "0.25rem",
    "--radius-row": "0.375rem",
    "--radius-control": "0.5rem",
    "--radius-panel": "0.625rem",
    "--radius-sheet": "0.75rem",
    "--font-sans":
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", Inter, "Segoe UI", sans-serif',
  },
  dark: {
    "--accent-food": "#e5ad88",
    "--accent-water": "#8ac3e8",
    "--accent-supplement": "#98d5a3",
    "--accent-workout": "#aaaaf0",
    "--accent-training-hero": "#80d5c2",
    "--accent-progress": "#d7aad7",
    "--accent-health": "#83ccdd",
    "--status-success": "#86cf9d",
    "--status-warning": "#eaca83",
    "--status-error": "#eba5b5",
    "--macro-protein": "#e5ad88",
    "--macro-carbs": "#8ac3e8",
    "--macro-fat": "#d7aad7",
    "--surface-app": "#121416",
    "--surface-panel": "#1a1d20",
    "--surface-raised": "#22262a",
    "--surface-elevated": "#292e33",
    "--surface-canvas": "#0e1012",
    "--secondary": "#262b30",
    "--muted": "#262b30",
    "--accent": "#262b30",
    "--hero-wash-tint": "10%",
    "--hero-mesh-tint": "18%",
    "--radius": "0.25rem",
    "--radius-row": "0.375rem",
    "--radius-control": "0.5rem",
    "--radius-panel": "0.625rem",
    "--radius-sheet": "0.75rem",
    "--font-sans":
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", Inter, "Segoe UI", sans-serif',
  },
})

export const FOREST_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "forest",
  label: "Forest",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  tokens: {
    "--identity-home-gradient":
      "radial-gradient(88% 72% at 2% -8%, color-mix(in oklab, var(--accent-training-hero) 38%, transparent) 0%, transparent 70%), radial-gradient(76% 70% at 102% 14%, color-mix(in oklab, var(--accent-food) 29%, transparent) 0%, transparent 72%), linear-gradient(180deg, color-mix(in oklab, var(--accent-supplement) 16%, transparent) 0%, transparent 64%)",
    "--identity-page-gradient":
      "radial-gradient(92% 74% at 4% -6%, color-mix(in oklab, var(--hero-accent, var(--accent-food)) 40%, transparent) 0%, transparent 70%), radial-gradient(74% 72% at 104% 28%, color-mix(in oklab, var(--accent-food) 24%, transparent) 0%, transparent 74%), linear-gradient(180deg, color-mix(in oklab, var(--accent-supplement) 17%, transparent) 0%, transparent 66%)",
    "--identity-hero-mask":
      "linear-gradient(180deg, #000 0%, #000 52%, transparent 96%)",
    "--identity-hero-height": "min(50rem, 88svh)",
  },
  light: {
    "--accent-food": "#8a6d1a",
    "--accent-food-bg": "color-mix(in srgb, #8a6d1a 8%, transparent)",
    "--accent-water": "#1e7a6e",
    "--accent-water-bg": "color-mix(in srgb, #1e7a6e 8%, transparent)",
    "--accent-supplement": "#3d8b37",
    "--accent-supplement-bg": "color-mix(in srgb, #3d8b37 8%, transparent)",
    "--accent-workout": "#2f6b4f",
    "--accent-workout-bg": "color-mix(in srgb, #2f6b4f 8%, transparent)",
    "--accent-training-hero": "#2e7d4f",
    "--accent-progress": "#6b8e4e",
    "--accent-health": "#2e8b57",
    "--accent-retro": "#96700a",
    "--accent-retro-bg": "color-mix(in srgb, #96700a 14%, transparent)",
    "--accent-schedule": "#3f7d5d",
    "--accent-schedule-bg": "color-mix(in srgb, #3f7d5d 15%, transparent)",
    "--accent-progress-bg": "color-mix(in srgb, #6b8e4e 8%, transparent)",
    "--status-success": "#2f7d3a",
    "--status-warning": "#96700a",
    "--status-error": "#9e3a32",
    "--macro-protein": "#8a6d1a",
    "--macro-carbs": "#1e7a6e",
    "--macro-fat": "#6b8e4e",
    "--surface-app": "#edf0e4",
    "--surface-panel": "#f7f9ef",
    "--surface-raised": "#fdfff7",
    "--surface-elevated": "#fdfff7",
    "--surface-canvas": "#e0e5d2",
    "--secondary": "#e3e7d6",
    "--muted": "#e3e7d6",
    "--accent": "#e3e7d6",
    "--hero-wash-tint": "34%",
    "--hero-mesh-tint": "32%",
    "--radius": "0.75rem",
    "--radius-row": "0.875rem",
    "--radius-control": "1.125rem",
    "--radius-panel": "1.375rem",
    "--radius-sheet": "1.75rem",
    "--font-sans":
      'ui-rounded, "SF Pro Rounded", "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
  },
  dark: {
    "--accent-food": "#a8cfbd",
    "--accent-water": "#8dcbdc",
    "--accent-supplement": "#acd5b3",
    "--accent-workout": "#85cfb0",
    "--accent-training-hero": "#8cd7c1",
    "--accent-progress": "#a8c6ce",
    "--accent-health": "#93d3c7",
    "--status-success": "#94d5b0",
    "--status-warning": "#e7c69b",
    "--status-error": "#eca6af",
    "--macro-protein": "#a8cfbd",
    "--macro-carbs": "#8dcbdc",
    "--macro-fat": "#a8c6ce",
    "--surface-app": "#121817",
    "--surface-panel": "#1a2220",
    "--surface-raised": "#222c29",
    "--surface-elevated": "#2a3531",
    "--surface-canvas": "#0e1413",
    "--secondary": "#26312e",
    "--muted": "#26312e",
    "--accent": "#26312e",
    "--hero-wash-tint": "13%",
    "--hero-mesh-tint": "22%",
    "--radius": "0.75rem",
    "--radius-row": "0.875rem",
    "--radius-control": "1.125rem",
    "--radius-panel": "1.375rem",
    "--radius-sheet": "1.75rem",
    "--font-sans":
      'ui-rounded, "SF Pro Rounded", "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
  },
})

export const OCEAN_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "ocean",
  label: "Ocean",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  tokens: {
    "--identity-home-gradient":
      "radial-gradient(118% 54% at 50% -10%, color-mix(in oklab, var(--accent-water) 42%, transparent) 0%, transparent 72%), radial-gradient(92% 48% at 104% 38%, color-mix(in oklab, var(--accent-training-hero) 28%, transparent) 0%, transparent 76%), linear-gradient(180deg, color-mix(in oklab, var(--accent-progress) 16%, transparent) 0%, transparent 68%)",
    "--identity-page-gradient":
      "radial-gradient(124% 58% at 50% -8%, color-mix(in oklab, var(--hero-accent, var(--accent-food)) 46%, transparent) 0%, transparent 72%), radial-gradient(96% 46% at 108% 40%, color-mix(in oklab, var(--accent-water) 26%, transparent) 0%, transparent 76%), linear-gradient(180deg, color-mix(in oklab, var(--accent-training-hero) 15%, transparent) 0%, transparent 70%)",
    "--identity-hero-mask":
      "linear-gradient(180deg, #000 0%, #000 48%, transparent 94%)",
    "--identity-hero-height": "min(46rem, 80svh)",
  },
  light: {
    "--accent-food": "#c05a2e",
    "--accent-food-bg": "color-mix(in srgb, #c05a2e 8%, transparent)",
    "--accent-water": "#1668a8",
    "--accent-water-bg": "color-mix(in srgb, #1668a8 8%, transparent)",
    "--accent-supplement": "#1a8a8a",
    "--accent-supplement-bg": "color-mix(in srgb, #1a8a8a 8%, transparent)",
    "--accent-workout": "#3f5fa8",
    "--accent-workout-bg": "color-mix(in srgb, #3f5fa8 8%, transparent)",
    "--accent-training-hero": "#0f7d8a",
    "--accent-progress": "#4f7fb8",
    "--accent-health": "#166e9e",
    "--accent-retro": "#8a6d1a",
    "--accent-retro-bg": "color-mix(in srgb, #8a6d1a 14%, transparent)",
    "--accent-schedule": "#2f6fa8",
    "--accent-schedule-bg": "color-mix(in srgb, #2f6fa8 15%, transparent)",
    "--accent-progress-bg": "color-mix(in srgb, #4f7fb8 8%, transparent)",
    "--status-success": "#1f7d5c",
    "--status-warning": "#96700a",
    "--status-error": "#a8324a",
    "--macro-protein": "#c05a2e",
    "--macro-carbs": "#1668a8",
    "--macro-fat": "#4f7fb8",
    "--surface-app": "#e9eff4",
    "--surface-panel": "#f4f8fb",
    "--surface-raised": "#fdfeff",
    "--surface-elevated": "#fdfeff",
    "--surface-canvas": "#dbe4ec",
    "--secondary": "#dde6ee",
    "--muted": "#dde6ee",
    "--accent": "#dde6ee",
    "--hero-wash-tint": "36%",
    "--hero-mesh-tint": "32%",
    "--radius": "0.5rem",
    "--radius-row": "0.5rem",
    "--radius-control": "0.75rem",
    "--radius-panel": "1rem",
    "--radius-sheet": "1.5rem",
    "--font-sans":
      '"Avenir Next", Avenir, "SF Pro Text", "Segoe UI", sans-serif',
  },
  dark: {
    "--accent-food": "#f5ae82",
    "--accent-water": "#83beee",
    "--accent-supplement": "#85ddd1",
    "--accent-workout": "#a2b1f7",
    "--accent-training-hero": "#7ad2dd",
    "--accent-progress": "#a2cef0",
    "--accent-health": "#81cde9",
    "--status-success": "#83dda9",
    "--status-warning": "#efca83",
    "--status-error": "#f5a2b2",
    "--macro-protein": "#f5ae82",
    "--macro-carbs": "#83beee",
    "--macro-fat": "#a2cef0",
    "--surface-app": "#101419",
    "--surface-panel": "#181e24",
    "--surface-raised": "#1e272f",
    "--surface-elevated": "#253039",
    "--surface-canvas": "#0c1014",
    "--secondary": "#222c35",
    "--muted": "#222c35",
    "--accent": "#222c35",
    "--hero-wash-tint": "20%",
    "--hero-mesh-tint": "30%",
    "--radius": "0.5rem",
    "--radius-row": "0.5rem",
    "--radius-control": "0.75rem",
    "--radius-panel": "1rem",
    "--radius-sheet": "1.5rem",
    "--font-sans":
      '"Avenir Next", Avenir, "SF Pro Text", "Segoe UI", sans-serif',
  },
})

export const BLOSSOM_PALETTE: VisualIdentity = defineVisualIdentity({
  id: "blossom",
  label: "Blossom",
  assets: {
    appName: "OneRep",
    appIconSrc: "/app-icon.svg",
  },
  tokens: {
    "--identity-home-gradient":
      "radial-gradient(64% 70% at 8% -2%, color-mix(in oklab, var(--accent-progress) 40%, transparent) 0%, transparent 70%), radial-gradient(66% 72% at 94% 4%, color-mix(in oklab, var(--accent-food) 36%, transparent) 0%, transparent 72%), radial-gradient(82% 52% at 54% 38%, color-mix(in oklab, var(--accent-water) 22%, transparent) 0%, transparent 78%)",
    "--identity-page-gradient":
      "radial-gradient(68% 74% at 6% -4%, color-mix(in oklab, var(--hero-accent, var(--accent-food)) 46%, transparent) 0%, transparent 70%), radial-gradient(64% 70% at 98% 10%, color-mix(in oklab, var(--accent-progress) 36%, transparent) 0%, transparent 72%), radial-gradient(82% 50% at 52% 42%, color-mix(in oklab, var(--accent-water) 20%, transparent) 0%, transparent 78%)",
    "--identity-hero-mask":
      "linear-gradient(180deg, #000 0%, #000 44%, transparent 92%)",
    "--identity-hero-height": "min(49rem, 86svh)",
  },
  light: {
    "--accent-food": "#b23a5b",
    "--accent-food-bg": "color-mix(in srgb, #b23a5b 8%, transparent)",
    "--accent-water": "#5b6fb0",
    "--accent-water-bg": "color-mix(in srgb, #5b6fb0 8%, transparent)",
    "--accent-supplement": "#3f8b66",
    "--accent-supplement-bg": "color-mix(in srgb, #3f8b66 8%, transparent)",
    "--accent-workout": "#8b4a8b",
    "--accent-workout-bg": "color-mix(in srgb, #8b4a8b 8%, transparent)",
    "--accent-training-hero": "#a83a6b",
    "--accent-progress": "#c06a9e",
    "--accent-health": "#93386b",
    "--accent-retro": "#a8760a",
    "--accent-retro-bg": "color-mix(in srgb, #a8760a 14%, transparent)",
    "--accent-schedule": "#7a5f9e",
    "--accent-schedule-bg": "color-mix(in srgb, #7a5f9e 15%, transparent)",
    "--accent-progress-bg": "color-mix(in srgb, #c06a9e 8%, transparent)",
    "--status-success": "#3f8b5c",
    "--status-warning": "#a8760a",
    "--status-error": "#a82e4a",
    "--macro-protein": "#b23a5b",
    "--macro-carbs": "#5b6fb0",
    "--macro-fat": "#c06a9e",
    "--surface-app": "#f5ecef",
    "--surface-panel": "#fdf5f7",
    "--surface-raised": "#fffdfd",
    "--surface-elevated": "#fffdfd",
    "--surface-canvas": "#eadde2",
    "--secondary": "#eadfe3",
    "--muted": "#eadfe3",
    "--accent": "#eadfe3",
    "--hero-wash-tint": "40%",
    "--hero-wash-crown": "18%",
    "--hero-mesh-tint": "36%",
    "--radius": "1rem",
    "--radius-row": "1rem",
    "--radius-control": "1.25rem",
    "--radius-panel": "1.5rem",
    "--radius-sheet": "2rem",
    "--font-sans":
      'ui-rounded, "SF Pro Rounded", "Hiragino Maru Gothic ProN", "Segoe UI", Roboto, sans-serif',
  },
  dark: {
    "--accent-food": "#f6a3b4",
    "--accent-water": "#b0b4f2",
    "--accent-supplement": "#91deb4",
    "--accent-workout": "#d6a9e6",
    "--accent-training-hero": "#f79fba",
    "--accent-progress": "#efbeda",
    "--accent-health": "#cba9f1",
    "--status-success": "#91e3b4",
    "--status-warning": "#efca83",
    "--status-error": "#f5a2ad",
    "--macro-protein": "#f6a3b4",
    "--macro-carbs": "#b0b4f2",
    "--macro-fat": "#efbeda",
    "--surface-app": "#161114",
    "--surface-panel": "#20191d",
    "--surface-raised": "#292126",
    "--surface-elevated": "#32282e",
    "--surface-canvas": "#120d10",
    "--secondary": "#2c2329",
    "--muted": "#2c2329",
    "--accent": "#2c2329",
    "--hero-wash-tint": "22%",
    "--hero-mesh-tint": "32%",
    "--radius": "1rem",
    "--radius-row": "1rem",
    "--radius-control": "1.25rem",
    "--radius-panel": "1.5rem",
    "--radius-sheet": "2rem",
    "--font-sans":
      'ui-rounded, "SF Pro Rounded", "Hiragino Maru Gothic ProN", "Segoe UI", Roboto, sans-serif',
  },
})

/** All registered palettes. The first entry is the default. */
export const PALETTES: readonly VisualIdentity[] = [
  ONEREPALETTE,
  DUSK_PALETTE,
  SLATE_PALETTE,
  FOREST_PALETTE,
  OCEAN_PALETTE,
  BLOSSOM_PALETTE,
] as const
