name: onerep

networks:
  coolify:
    external: true

services:
  web:
    image: nginx:1.29-alpine
    container_name: onerep-web
    restart: unless-stopped
    networks:
      - coolify
    volumes:
      - /data/onerep/web:/usr/share/nginx/html:ro
      - /data/onerep/nginx-spa.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.routers.onerep-web-http.entrypoints=http
      - traefik.http.routers.onerep-web-http.rule=Host(`onerep.life`)
      - traefik.http.routers.onerep-web-http.service=onerep-web
      - traefik.http.routers.onerep-web-https.entrypoints=https
      - traefik.http.routers.onerep-web-https.rule=Host(`onerep.life`)
      - traefik.http.routers.onerep-web-https.tls=true
      - traefik.http.routers.onerep-web-https.tls.certresolver=letsencrypt
      - traefik.http.routers.onerep-web-https.service=onerep-web
      - traefik.http.services.onerep-web.loadbalancer.server.port=80

  app:
    image: nginx:1.29-alpine
    container_name: onerep-app
    restart: unless-stopped
    networks:
      - coolify
    volumes:
      - /data/onerep/app:/usr/share/nginx/html:ro
      - /data/onerep/nginx-spa.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.routers.onerep-app-http.entrypoints=http
      - traefik.http.routers.onerep-app-http.rule=Host(`app.onerep.life`)
      - traefik.http.routers.onerep-app-http.service=onerep-app
      - traefik.http.routers.onerep-app-https.entrypoints=https
      - traefik.http.routers.onerep-app-https.rule=Host(`app.onerep.life`)
      - traefik.http.routers.onerep-app-https.tls=true
      - traefik.http.routers.onerep-app-https.tls.certresolver=letsencrypt
      - traefik.http.routers.onerep-app-https.service=onerep-app
      - traefik.http.services.onerep-app.loadbalancer.server.port=80
