import { tr } from "@repo/ui/i18n"

// Explicit keys keep the adaptive question bank visible to translation extraction.
export function extraGuideCopy(): Record<string, string> {
  return {
    "Is a bench available?": tr("Is a bench available?"),
    "Adjustable bench": tr("Adjustable bench"),
    "Flat bench": tr("Flat bench"),
    "No bench": tr("No bench"),
    "Can you use a squat rack?": tr("Can you use a squat rack?"),
    "Rack with safety bars": tr("Rack with safety bars"),
    "Rack without safety bars": tr("Rack without safety bars"),
    "No rack": tr("No rack"),
    "What cable setup is available?": tr("What cable setup is available?"),
    "Adjustable cable station": tr("Adjustable cable station"),
    "Fixed pulldown station": tr("Fixed pulldown station"),
    "No cables": tr("No cables"),
    "Is there a pull-up station?": tr("Is there a pull-up station?"),
    "Bar with assistance machine": tr("Bar with assistance machine"),
    "Bar with bands": tr("Bar with bands"),
    "Unassisted bar only": tr("Unassisted bar only"),
    "No pull-up bar": tr("No pull-up bar"),
    "Which leg machines are available?": tr(
      "Which leg machines are available?",
    ),
    "Leg press and leg curl": tr("Leg press and leg curl"),
    "Leg press only": tr("Leg press only"),
    "Leg curl only": tr("Leg curl only"),
    Neither: tr("Neither"),
    "What resistance bands do you have?": tr(
      "What resistance bands do you have?",
    ),
    "Long bands": tr("Long bands"),
    "Mini bands": tr("Mini bands"),
    "Both types": tr("Both types"),
    "No bands": tr("No bands"),
    "How much choice do your dumbbells offer?": tr(
      "How much choice do your dumbbells offer?",
    ),
    "Several weights": tr("Several weights"),
    "One light pair": tr("One light pair"),
    "One challenging pair": tr("One challenging pair"),
    "Which barbell setup is available?": tr(
      "Which barbell setup is available?",
    ),
    "Straight barbell": tr("Straight barbell"),
    "Trap bar": tr("Trap bar"),
    Both: tr("Both"),
    "Are kettlebells available?": tr("Are kettlebells available?"),
    "One kettlebell": tr("One kettlebell"),
    "No kettlebells": tr("No kettlebells"),
    "What can you use for supported rows?": tr(
      "What can you use for supported rows?",
    ),
    "Chest-supported machine": tr("Chest-supported machine"),
    "Incline bench and dumbbells": tr("Incline bench and dumbbells"),
    "What is available for conditioning?": tr(
      "What is available for conditioning?",
    ),
    Bike: tr("Bike"),
    Rower: tr("Rower"),
    Treadmill: tr("Treadmill"),
    "No cardio equipment": tr("No cardio equipment"),
    "Is a landmine attachment available?": tr(
      "Is a landmine attachment available?",
    ),
    "Yes, with handles": tr("Yes, with handles"),
    "Yes, without handles": tr("Yes, without handles"),
    No: tr("No"),
    "What can you use for calf work?": tr("What can you use for calf work?"),
    "Calf machine": tr("Calf machine"),
    "Step and dumbbells": tr("Step and dumbbells"),
    "Flat floor only": tr("Flat floor only"),
    "What floor space can you use?": tr("What floor space can you use?"),
    "Exercise mat": tr("Exercise mat"),
    "Soft gym flooring": tr("Soft gym flooring"),
    "Hard floor only": tr("Hard floor only"),
    "Is there stable support for bodyweight work?": tr(
      "Is there stable support for bodyweight work?",
    ),
    "Fixed bench": tr("Fixed bench"),
    "Sturdy counter": tr("Sturdy counter"),
    "How small are your weight changes?": tr(
      "How small are your weight changes?",
    ),
    "Small increments available": tr("Small increments available"),
    "Only large jumps": tr("Only large jumps"),
    "Fixed resistance": tr("Fixed resistance"),
    "Which chest angle would you like to emphasize?": tr(
      "Which chest angle would you like to emphasize?",
    ),
    "Incline pressing": tr("Incline pressing"),
    "Flat pressing": tr("Flat pressing"),
    "A mix of angles": tr("A mix of angles"),
    "What feels most familiar for chest presses?": tr(
      "What feels most familiar for chest presses?",
    ),
    Dumbbells: tr("Dumbbells"),
    Barbell: tr("Barbell"),
    "Chest press machine": tr("Chest press machine"),
    "No preference": tr("No preference"),
    "Will someone spot your barbell presses?": tr(
      "Will someone spot your barbell presses?",
    ),
    "A spotter is available": tr("A spotter is available"),
    "I will use safety bars": tr("I will use safety bars"),
    "Choose another press": tr("Choose another press"),
    "Which push-up variation is manageable?": tr(
      "Which push-up variation is manageable?",
    ),
    "Hands elevated": tr("Hands elevated"),
    "From knees": tr("From knees"),
    "Standard push-ups": tr("Standard push-ups"),
    "Choose another chest exercise": tr("Choose another chest exercise"),
    "How would you like to approach pull-ups?": tr(
      "How would you like to approach pull-ups?",
    ),
    "Assisted repetitions": tr("Assisted repetitions"),
    "Unassisted repetitions": tr("Unassisted repetitions"),
    "Use pulldowns instead": tr("Use pulldowns instead"),
    "Which pulling direction should lead?": tr(
      "Which pulling direction should lead?",
    ),
    "Vertical pulls": tr("Vertical pulls"),
    "Horizontal rows": tr("Horizontal rows"),
    "Give both equal time": tr("Give both equal time"),
    "How would you prefer to row?": tr("How would you prefer to row?"),
    "Chest supported": tr("Chest supported"),
    "One hand supported": tr("One hand supported"),
    Unsupported: tr("Unsupported"),
    "Which shoulder work deserves more time?": tr(
      "Which shoulder work deserves more time?",
    ),
    "Side raises": tr("Side raises"),
    "Rear delt work": tr("Rear delt work"),
    "Overhead presses": tr("Overhead presses"),
    "What would you use for overhead presses?": tr(
      "What would you use for overhead presses?",
    ),
    Machine: tr("Machine"),
    "How would you like to train biceps?": tr(
      "How would you like to train biceps?",
    ),
    "Standing curls": tr("Standing curls"),
    "Supported curls": tr("Supported curls"),
    "Cable curls": tr("Cable curls"),
    "Which triceps exercise style do you prefer?": tr(
      "Which triceps exercise style do you prefer?",
    ),
    "Cable pressdowns": tr("Cable pressdowns"),
    "Lying extensions": tr("Lying extensions"),
    "Close-grip presses": tr("Close-grip presses"),
    "How much direct arm work fits today?": tr(
      "How much direct arm work fits today?",
    ),
    "One biceps and one triceps exercise": tr(
      "One biceps and one triceps exercise",
    ),
    "One arm exercise total": tr("One arm exercise total"),
    "Compound exercises only": tr("Compound exercises only"),
    "Should this session include direct grip work?": tr(
      "Should this session include direct grip work?",
    ),
    "Loaded holds": tr("Loaded holds"),
    "Wrist and forearm work": tr("Wrist and forearm work"),
    "No direct grip work": tr("No direct grip work"),
    "Would you rather press seated or standing?": tr(
      "Would you rather press seated or standing?",
    ),
    Seated: tr("Seated"),
    Standing: tr("Standing"),
    "Which pulling grip do you prefer?": tr(
      "Which pulling grip do you prefer?",
    ),
    "Palms facing each other": tr("Palms facing each other"),
    "Palms facing away": tr("Palms facing away"),
    "Palms facing you": tr("Palms facing you"),
    "Should upper body work include single-arm sets?": tr(
      "Should upper body work include single-arm sets?",
    ),
    "One single-arm exercise": tr("One single-arm exercise"),
    "Several single-arm exercises": tr("Several single-arm exercises"),
    "Both arms together": tr("Both arms together"),
    "Which squat setup do you prefer?": tr("Which squat setup do you prefer?"),
    "Goblet squat": tr("Goblet squat"),
    "Barbell squat": tr("Barbell squat"),
    "Squat machine": tr("Squat machine"),
    "Which hip hinge is familiar?": tr("Which hip hinge is familiar?"),
    "Romanian deadlift": tr("Romanian deadlift"),
    "Trap bar deadlift": tr("Trap bar deadlift"),
    "Cable pull-through": tr("Cable pull-through"),
    "None yet": tr("None yet"),
    "Which single-leg movement would you choose?": tr(
      "Which single-leg movement would you choose?",
    ),
    "Split squat": tr("Split squat"),
    "Step-up": tr("Step-up"),
    "Reverse lunge": tr("Reverse lunge"),
    "Keep both feet planted": tr("Keep both feet planted"),
    "Would you like support for single-leg work?": tr(
      "Would you like support for single-leg work?",
    ),
    "Use a rail or rack": tr("Use a rail or rack"),
    "Use bodyweight without support": tr("Use bodyweight without support"),
    "Skip single-leg work": tr("Skip single-leg work"),
    "How should hamstring work be split?": tr(
      "How should hamstring work be split?",
    ),
    "More leg curls": tr("More leg curls"),
    "More hip hinges": tr("More hip hinges"),
    "Equal time for both": tr("Equal time for both"),
    "What glute bridge setup can you use?": tr(
      "What glute bridge setup can you use?",
    ),
    "Hip thrust machine": tr("Hip thrust machine"),
    "Bench and weights": tr("Bench and weights"),
    "Floor bridge only": tr("Floor bridge only"),
    "Which calf work would you like?": tr("Which calf work would you like?"),
    "Straight-leg raises": tr("Straight-leg raises"),
    "Bent-knee raises": tr("Bent-knee raises"),
    "How familiar are barbell squats?": tr("How familiar are barbell squats?"),
    "Comfortable with the setup": tr("Comfortable with the setup"),
    "Still learning the setup": tr("Still learning the setup"),
    "Use a simpler alternative": tr("Use a simpler alternative"),
    "Where would you prefer to start your deadlifts?": tr(
      "Where would you prefer to start your deadlifts?",
    ),
    "From the floor": tr("From the floor"),
    "From raised blocks": tr("From raised blocks"),
    "Use a Romanian deadlift instead": tr("Use a Romanian deadlift instead"),
    "Which glute accessory appeals to you?": tr(
      "Which glute accessory appeals to you?",
    ),
    "Hip abduction": tr("Hip abduction"),
    "Cable kickbacks": tr("Cable kickbacks"),
    "Glute bridges": tr("Glute bridges"),
    "No extra glute exercise": tr("No extra glute exercise"),
    "Can you use a leg extension machine?": tr(
      "Can you use a leg extension machine?",
    ),
    "Yes, both legs together": tr("Yes, both legs together"),
    "Yes, one leg at a time": tr("Yes, one leg at a time"),
    "No machine available": tr("No machine available"),
    "How should lower body work begin?": tr(
      "How should lower body work begin?",
    ),
    "Knee-dominant movement": tr("Knee-dominant movement"),
    "Hip-dominant movement": tr("Hip-dominant movement"),
    "Single-leg movement": tr("Single-leg movement"),
    "What kind of core work would you like?": tr(
      "What kind of core work would you like?",
    ),
    "Resist arching": tr("Resist arching"),
    "Resist rotation": tr("Resist rotation"),
    "Controlled trunk curls": tr("Controlled trunk curls"),
    "A mix": tr("A mix"),
    "How do you prefer core sets?": tr("How do you prefer core sets?"),
    "Timed holds": tr("Timed holds"),
    "Counted repetitions": tr("Counted repetitions"),
    "A mix of both": tr("A mix of both"),
    "Which position suits your core work?": tr(
      "Which position suits your core work?",
    ),
    "On the floor": tr("On the floor"),
    Hanging: tr("Hanging"),
    "Which plank variation suits you?": tr("Which plank variation suits you?"),
    "Knees down": tr("Knees down"),
    "Full plank": tr("Full plank"),
    "Choose another exercise": tr("Choose another exercise"),
    "Should core work include rotation?": tr(
      "Should core work include rotation?",
    ),
    "Controlled rotation": tr("Controlled rotation"),
    "Resist rotation only": tr("Resist rotation only"),
    "No rotational work": tr("No rotational work"),
    "Do you have room for loaded carries?": tr(
      "Do you have room for loaded carries?",
    ),
    "A clear walking lane": tr("A clear walking lane"),
    "Room to march in place": tr("Room to march in place"),
    "Use stationary holds": tr("Use stationary holds"),
    "What kind of carry would you prefer?": tr(
      "What kind of carry would you prefer?",
    ),
    "Weights in both hands": tr("Weights in both hands"),
    "Weight on one side": tr("Weight on one side"),
    "Weights at the chest": tr("Weights at the chest"),
    "No carries": tr("No carries"),
    "Where should core work sit?": tr("Where should core work sit?"),
    "Brief work near the start": tr("Brief work near the start"),
    "Between accessory exercises": tr("Between accessory exercises"),
    "At the end": tr("At the end"),
    "What repetition range do you enjoy?": tr(
      "What repetition range do you enjoy?",
    ),
    "Lower reps with longer rests": tr("Lower reps with longer rests"),
    "Moderate reps": tr("Moderate reps"),
    "Higher reps with lighter loads": tr("Higher reps with lighter loads"),
    "Choose for my goal": tr("Choose for my goal"),
    "How should the work be distributed?": tr(
      "How should the work be distributed?",
    ),
    "More sets on fewer exercises": tr("More sets on fewer exercises"),
    "Fewer sets across more exercises": tr("Fewer sets across more exercises"),
    "A balance": tr("A balance"),
    "Would you like paired exercises?": tr("Would you like paired exercises?"),
    "Pair different muscle groups": tr("Pair different muscle groups"),
    "Pair only small accessories": tr("Pair only small accessories"),
    "Keep all exercises separate": tr("Keep all exercises separate"),
    "Have you warmed up already?": tr("Have you warmed up already?"),
    "Not yet": tr("Not yet"),
    "General warm-up done": tr("General warm-up done"),
    "Ready for exercise-specific warm-ups": tr(
      "Ready for exercise-specific warm-ups",
    ),
    "How would you like to warm up?": tr("How would you like to warm up?"),
    "Easy cardio then ramp-up sets": tr("Easy cardio then ramp-up sets"),
    "Movement practice then ramp-up sets": tr(
      "Movement practice then ramp-up sets",
    ),
    "Ramp-up sets only": tr("Ramp-up sets only"),
    "How much ramp-up work do you prefer?": tr(
      "How much ramp-up work do you prefer?",
    ),
    "Several gradual warm-up sets": tr("Several gradual warm-up sets"),
    "A couple of warm-up sets": tr("A couple of warm-up sets"),
    "Choose for the first lift": tr("Choose for the first lift"),
    "How much setup should accessories need?": tr(
      "How much setup should accessories need?",
    ),
    "Very little setup": tr("Very little setup"),
    "Some setup is fine": tr("Some setup is fine"),
    "Choose for the target muscles": tr("Choose for the target muscles"),
    "How many exercises feel manageable?": tr(
      "How many exercises feel manageable?",
    ),
    "Three or four": tr("Three or four"),
    "Five or six": tr("Five or six"),
    "Choose to fit my time": tr("Choose to fit my time"),
    "Would you like tempo instructions?": tr(
      "Would you like tempo instructions?",
    ),
    "Simple controlled repetitions": tr("Simple controlled repetitions"),
    "A slower lowering phase": tr("A slower lowering phase"),
    "Brief pauses on selected exercises": tr(
      "Brief pauses on selected exercises",
    ),
    "How would you like repetition targets?": tr(
      "How would you like repetition targets?",
    ),
    "One target per set": tr("One target per set"),
    "A small target range": tr("A small target range"),
    "Timed sets where appropriate": tr("Timed sets where appropriate"),
    "How should the main exercise be organized?": tr(
      "How should the main exercise be organized?",
    ),
    "Same rep target each set": tr("Same rep target each set"),
    "One main set then lighter sets": tr("One main set then lighter sets"),
    "Technique-focused sets": tr("Technique-focused sets"),
    "How much isolation work would you like?": tr(
      "How much isolation work would you like?",
    ),
    "Mostly compound movements": tr("Mostly compound movements"),
    "A balanced mix": tr("A balanced mix"),
    "More targeted accessories": tr("More targeted accessories"),
    "How busy is the gym?": tr("How busy is the gym?"),
    "Plenty of equipment free": tr("Plenty of equipment free"),
    "Some stations may be taken": tr("Some stations may be taken"),
    "Keep me at one station": tr("Keep me at one station"),
    "How often would you like to change stations?": tr(
      "How often would you like to change stations?",
    ),
    "As little as possible": tr("As little as possible"),
    "A few changes are fine": tr("A few changes are fine"),
    "How often do you want to get onto the floor?": tr(
      "How often do you want to get onto the floor?",
    ),
    "Keep all work standing or seated": tr("Keep all work standing or seated"),
    "Group floor exercises together": tr("Group floor exercises together"),
    "Does the session need to stay quiet?": tr(
      "Does the session need to stay quiet?",
    ),
    "Yes, quiet movements only": tr("Yes, quiet movements only"),
    "Some noise is fine": tr("Some noise is fine"),
    "No noise limit": tr("No noise limit"),
    "How much room do you have?": tr("How much room do you have?"),
    "Enough for a mat": tr("Enough for a mat"),
    "Room to step and lunge": tr("Room to step and lunge"),
    "A full training area": tr("A full training area"),
    "Are you sharing equipment today?": tr("Are you sharing equipment today?"),
    "Training alone": tr("Training alone"),
    "Alternating sets with one person": tr("Alternating sets with one person"),
    "Sharing with a group": tr("Sharing with a group"),
    "How much weight changing is practical?": tr(
      "How much weight changing is practical?",
    ),
    "Keep one setup where possible": tr("Keep one setup where possible"),
    "Occasional changes": tr("Occasional changes"),
    "Change freely": tr("Change freely"),
    "Can you follow timed sets and rests?": tr(
      "Can you follow timed sets and rests?",
    ),
    "I can use a timer": tr("I can use a timer"),
    "I prefer rep counts": tr("I prefer rep counts"),
    "Either works": tr("Either works"),
    "What upper body work did you do last time?": tr(
      "What upper body work did you do last time?",
    ),
    "Mostly pressing": tr("Mostly pressing"),
    "Mostly pulling": tr("Mostly pulling"),
    "No recent upper body work": tr("No recent upper body work"),
    "What lower body work did you do last time?": tr(
      "What lower body work did you do last time?",
    ),
    "Mostly squats or lunges": tr("Mostly squats or lunges"),
    "Mostly hinges or curls": tr("Mostly hinges or curls"),
    "No recent lower body work": tr("No recent lower body work"),
    "When do you expect to train again?": tr(
      "When do you expect to train again?",
    ),
    Tomorrow: tr("Tomorrow"),
    "In two or three days": tr("In two or three days"),
    "Later in the week": tr("Later in the week"),
    "Not sure": tr("Not sure"),
    "Are you returning after a training break?": tr(
      "Are you returning after a training break?",
    ),
    "No, training consistently": tr("No, training consistently"),
    "After a short break": tr("After a short break"),
    "After a longer break": tr("After a longer break"),
    "Is this alongside another session today?": tr(
      "Is this alongside another session today?",
    ),
    "Strength only today": tr("Strength only today"),
    "Before cardio or sport": tr("Before cardio or sport"),
    "After cardio or sport": tr("After cardio or sport"),
    "Is this workout meant to be repeated?": tr(
      "Is this workout meant to be repeated?",
    ),
    "A regular repeatable session": tr("A regular repeatable session"),
    "A one-off workout": tr("A one-off workout"),
    "Not decided": tr("Not decided"),
    "What should be easiest to compare next time?": tr(
      "What should be easiest to compare next time?",
    ),
    "Main lift repetitions": tr("Main lift repetitions"),
    "Main lift load": tr("Main lift load"),
    "Total completed sets": tr("Total completed sets"),
    "No tracking preference": tr("No tracking preference"),
    "Would you like extra practice on one pattern?": tr(
      "Would you like extra practice on one pattern?",
    ),
    "Squat technique": tr("Squat technique"),
    "Hip hinge technique": tr("Hip hinge technique"),
    "Pressing technique": tr("Pressing technique"),
    "No extra practice": tr("No extra practice"),
  }
}
