# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload an existing IPA to TestFlight"
  lane :beta do |options|
    ipa = options[:ipa]
    UI.user_error!("Pass the IPA path with ipa:/path/to/app.ipa") if ipa.to_s.empty?

    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APP_STORE_CONNECT_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
      key_filepath: File.expand_path(
        "~/.appstoreconnect/private_keys/AuthKey_#{ENV.fetch('APP_STORE_CONNECT_KEY_ID')}.p8"
      )
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: ipa,
      skip_waiting_for_build_processing: true
    )
  end
end
