import { readFileSync, writeFileSync } from "node:fs";
import { coachOpenUILibrary } from "../apps/mobile/src/lib/coach-openui-library";

const prompt = coachOpenUILibrary.prompt({
  preamble:
    "The following language instructions apply ONLY to the openui string inside the Coach JSON response. The outer response must remain JSON with reply, openui, operations, artifacts and sleepMode.",
  additionalRules: [
    "Use 1-3 compact sections sized for a phone. Use only registered components.",
    "Use MealLog for editable meal logging and CoachGoal for goals the user may pin.",
    "Use Button actions with type continue_conversation to send choices and form state to the Coach, or a supported navigation action: open_nutrition, open_workouts, open_progress, open_settings, open_workout_builder, open_recipe_builder, open_supplements, log_food.",
    "Do not use Query, Mutation, external links, HTML, JavaScript, or automatic writes. App writes stay in the outer operations array or the explicit MealLog and CoachGoal controls.",
  ],
});
const outputs = [
  [
    new URL("../convex/ai/coachOpenUI.generated.ts", import.meta.url),
    `// Generated by scripts/generate-coach-openui.ts. Do not edit.\nexport const coachOpenUIPrompt = ${JSON.stringify(prompt)};\nexport const coachOpenUISchema = ${JSON.stringify(coachOpenUILibrary.toJSONSchema())};\n`,
  ],
] as const;
for (const [file, content] of outputs) {
  if (process.argv.includes("--check")) {
    if (readFileSync(file, "utf8") !== content)
      throw new Error(
        "Coach OpenUI instructions are stale. Run bun run prompts:generate",
      );
  } else writeFileSync(file, content);
}
